package constant;

import java.nio.file.Paths;

public class HuongDanSuDungConstant {
	public static final String TEST = "<!DOCTYPE html>\r\n" + "<html>\r\n" + "<head>\r\n"
			+ "	<title>Bài 7</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "	<p><img src='file:/"
			+ Paths.get("Img/img7.png").toAbsolutePath()
			+ "' width=\"70\" height=\"70\" alt=\"img\">A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<p><img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"middle\" width=\"70\" height=\"70\" alt=\"img\">A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<p><img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"top\" width=\"70\" height=\"70\" alt=\"img\">A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"right\" width=\"70\" height=\"70\" alt=\"img\">\r\n"
			+ "	<p>A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"left\" width=\"70\" height=\"70\" alt=\"img\">\r\n"
			+ "	<p>A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	\r\n" + "</body>\r\n" + "</html>";

	public static final String LAP_HOA_DON = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n" + "<!--\r\n"
			+ " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào nút “L&#7853;p hóa &#273;&#417;n” &#7903; giao di&#7879;n trang\r\n"
			+ "ch&#7911;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=680 height=363 id=\"Picture 1\"\r\n src='file:/"
			+ Paths.get("Img/LHD1.png").toAbsolutePath() + "'" + "</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#272;i&#7873;n thông tin s&#7889; CMT ho&#7863;c S&#272;T &#273;&#7875; l&#7845;y\r\n"
			+ "thông tin c&#7911;a khách hàng &#273;ã có s&#7861;n trong h&#7879; th&#7889;ng.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=363 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/LHD2.png").toAbsolutePath() + "'" + "\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>Khi thông tin c&#7911;a khách hàng d&#432;&#7907;c\r\n"
			+ "l&#7845;y lên nó s&#7867; có d&#7841;ng nh&#432; hình sau: </span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=364 id=\"Picture 3\"\r\n" + "src='file:"
			+ Paths.get("Img/LHD3.png").toAbsolutePath() + "'" + "\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B3</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n xe mà khách hàng mu&#7889;n &#273;&#7863;t sau &#273;ó ch&#7885;n\r\n"
			+ "vào nút “Thêm”, xe v&#7915;a thao tác s&#7867; &#273;&#432;&#7907;c thêm vào b&#7843;ng\r\n"
			+ "hóa &#273;&#417;n.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=680 height=389 id=\"Picture 4\"\r\n" + "src='file:/"
			+ Paths.get("Img/LHD4.png").toAbsolutePath() + "'" + "\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B4</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Nh&#7853;p ti&#7873;n khách tr&#7843; vào ô “Ti&#7873;n khách tr&#7843;, h&#7879;\r\n"
			+ "th&#7889;ng s&#7867; hi&#7879;n th&#7883; ti&#7873;n th&#7915;a &#7903; ô “Ti&#7873;n\r\n"
			+ "tr&#7843; l&#7841;i”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=366 id=\"Picture 5\"\r\n" + "src='file:/"
			+ Paths.get("Img/LHD5.png").toAbsolutePath() + "'" + "\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B5</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n nút “L&#7853;p hóa &#273;&#417;n”. Sau khi l&#7853;p hóa\r\n"
			+ "&#273;&#417;n thành công h&#7879; th&#7889;ng s&#7867; hi&#7875;n th&#7883; b&#7843;ng\r\n"
			+ "chi ti&#7871;t hóa &#273;&#417;n nh&#432; hình bên d&#432;&#7899;i.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=366 id=\"Picture 6\"\r\n" + "src='file:/"
			+ Paths.get("Img/LHD6.png").toAbsolutePath() + "'" + "\r\n"
			+ "alt=\"Graphical user interface, text, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	public static final String GIOI_THIEU = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n" + "<head>\r\n"
			+ "<meta charset=\"UTF-8\">\r\n"
			+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "<title>Giới thiệu</title>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body style=\"font-size: 20px;\">\r\n" + "<div>\r\n"
			+ "<h1 style=\"font-size: 35px;\">Giới thiệu</h1>\r\n"
			+ "<span>Quản lý mua bán xe máy tại cửa hàng Motor Cycle Việt Nam.</span> <br>\r\n"
			+ "<span>Version: 2020-11 (1.0.0.0)</span><br>\r\n"
			+ "<span>Giảng viên hướng dẫn: ThS. Trần Thị Anh Thi</span><br>\r\n" + "<span>Nhóm 7:</span><br>\r\n"
			+ "<ul>\r\n" + "<li>Huỳnh Anh Tiên - 18065341 (Nhóm trưởng)</li>\r\n"
			+ "<li>Nguyễn Trần Nhật Hào - 18055671</li>\r\n" + "<li>Trần Hoàng Phúc - 18072731</li>\r\n"
			+ "<li>Mai Thanh Trọng - 18064861</li>\r\n" + "</ul>\r\n" + "</div>\r\n" + "</body>\r\n" + "</html>";

//	public static final String TIM_KIEM_HOP_DONG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<head>\r\n"
//			+ "    <meta charset=\"UTF-8\">\r\n"
//			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
//			+ "    <title>Tìm kiếm hợp đồng</title>\r\n" + "</head>\r\n" + "<body>\r\n"
//			+ "    <div style=\"margin: 50px; font-size: 20px;\">\r\n" + "        <h1>Tìm kiếm hợp đồng</h1>\r\n"
//			+ "        <hr>\r\n" + "        <p>B1: Chọn vào tiêu chí muốn tìm kiếm.</p>\r\n"
//			+ "        <p>B2: Nhập thông tin bạn muốn tìm kiếm vào ô tìm kiếm.</p>\r\n" + "        <br>\r\n"
////			+ "        <img src='file:/" + Paths.get("Img/TimKiemHopDong1.png").toAbsolutePath() + "' alt=\"\">\r\n"
//			+ "        <img src='file:/" + Paths.get("Img/Tìm kiếm hợp đồng theo ngày tháng năm_1.png").toAbsolutePath()
//			+ "' alt=\"\">\r\n" + "        <br>\r\n"
//			+ "        <p>Chương trình sẻ hiện thị danh sách các hợp đồng tìm kiếm được theo tiêu chí đã được chọn.</p>\r\n"
//			+ "        <br>\r\n" + "        <img  src='file:/" + Paths.get("Img/TimKiemHopDong2.png").toAbsolutePath()
//			+ "' alt=\"\">\r\n" + "    </div>\r\n" + "</body>\r\n" + "</html>";

	public static final String TIM_KIEM_HOP_DONG_THEO_NGAY = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Tìm kiếm hợp đồng</title>\r\n" + "</head>\r\n" + "<body>\r\n"
			+ "    <div style=\"margin: 50px; font-size: 20px;\">\r\n" + "        <h1>Tìm kiếm hợp đồng</h1>\r\n"
			+ "        <hr>\r\n" + "        <p> Chọn vào ngày, tháng, năm muốn tìm kiếm hợp đồng</p>\r\n"
			+ "        <br>\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/TimKiemHopDongTheoNgay1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "        <br>\r\n"
			+ "        <p>Chương trình sẻ hiển thị danh sách hợp đồng tương ứng với ngày tìm kiếm</p>\r\n"
			+ "        <br>\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/TimKiemHopDongTheoNgay2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "    </div>\r\n"
			+ "</body>\r\n" + "</html>";

	public static final String XEM_CHI_TIET_HOP_DONG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Xem chi tiết hợp đồng</title>\r\n" + "</head>\r\n" + "<body>\r\n"
			+ "    <div style=\"margin: 50px; font-size: 20px;\">\r\n" + "        <h1>Xem chi tiết hợp đồng</h1>\r\n"
			+ "        <hr>\r\n" + "        <p>B1: Chọn vào hợp đồng mà bạn muốn xem chi tiết.</p>\r\n"
			+ "        <p>B2: Chọn vào nút “Xem chi tiết”</p>\r\n" + "        <br>\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/XemChiTietHopDong1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "        <br>\r\n"
			+ "        <p>Chương trình hiển thị bảng “Chi tiết hợp đồng xe máy”</p>\r\n" + "        <br>\r\n"
			+ "        <img  src='file:/" + Paths.get("Img/XemChiTietHopDong2.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    </div>\r\n" + "</body>\r\n" + "</html>";
	public static final String SUA_NHAN_VIEN_KY_THUAT = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Sửa nhân viên kĩ thuật</title>\r\n" + "</head>\r\n" + "<body>\r\n"
			+ "    <div style=\"margin: 50px; font-size: 20px;\">\r\n" + "        <h1>Sửa nhân viên kĩ thuật</h1>\r\n"
			+ "        <hr>\r\n"
			+ "        <p>B1: Ở bảng nhân viên kỹ thuật chọn nhân viên kĩ thuật muốn cập nhật.</p>\r\n"
			+ "        <p>B2: Chọn vào nút “Sửa”.</p>\r\n" + "        <br>\r\n"
			+ "        <img  src=\"../IMG/nhân viên kĩ thuật/SuaNVKT1.png\" alt=\"\">\r\n" + "        <br>\r\n"
			+ "        <p>B3: Chọn và điền các thông tin muốn cập nhật.</p>\r\n"
			+ "        <p>B4: Chọn vào nút sửa.</p>\r\n" + "        <p>B5: Xác nhận yêu cầu và chọn “yes”.</p>\r\n"
			+ "        <br>\r\n" + "        <img  src=\"../IMG/nhân viên kĩ thuật/SuaNVKT2.png\" alt=\"\">\r\n"
			+ "    </div>\r\n" + "</body>\r\n" + "</html>";

	// KHÁCH HÀNG
	public static final String SUA_KHACH_HANG = "<html>\r\n" + "\r\n" + "<head>\r\n" + "\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>B1: &#7902; giao di&#7879;n Qu&#7843;n lý\r\n"
			+ "khách hàng ch&#7885;n vào khách hàng b&#7841;n mu&#7889;n s&#7917;a và ch&#7885;n\r\n"
			+ "vào nút s&#7917;a.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=364 id=\"Picture 3\"\r\n" + "src='file:/"
			+ Paths.get("Img/SKH1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application, table, Excel&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>B2: S&#7917;a l&#7841;i các thông tin mà b&#7841;n\r\n"
			+ "mu&#7889;n thay &#273;&#7893;i trên giao di&#7879;n “C&#7853;p nh&#7853;t thông\r\n"
			+ "tin khách hàng” và ch&#7885;n nút “L&#432;u”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=366 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/SKH2.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>H&#7879; th&#7889;ng s&#7867; xu&#7845;t\r\n"
			+ "hi&#7879;n 1 yêu c&#7847;u &#273;&#7875; xác nh&#7853;n và khi ch&#7885;n “yes”\r\n"
			+ "thì s&#7917;a khách hàng &#273;ã thành công và s&#7867; hi&#7875;n th&#7883;\r\n"
			+ "thông báo nh&#432; hình bên.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=366 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/SKH3.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	public static final String TIM_KIEM_KHACH_HANG = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n" + "<!--\r\n"
			+ " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>B1: &#7902; trang qu&#7843;n lý khách hàng\r\n"
			+ "ch&#7885;n tiêu chí mà b&#7841;n mu&#7889;n tìm ki&#7871;m.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=368 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/TKKH1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>B2: Nh&#7853;p t&#7915; khóa b&#7841;n mu&#7889;n\r\n"
			+ "tìm ki&#7871;m và ô tìm ki&#7871;m</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>H&#7879; th&#7889;ng s&#7867; hi&#7875;n\r\n"
			+ "th&#7883; b&#7843;ng danh sách các k&#7871;t qu&#7843; tìm &#273;&#432;&#7907;c</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=366 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/TKKH2.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	public static final String THEM_KHACH_HANG = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n" + "<!--\r\n"
			+ " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>B1: &#7902; trang qu&#7843;n lý khách hàng\r\n"
			+ "ch&#7885;n nút “Thêm”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=363 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/TKH1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application, table&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>B2: &#272;i&#7875;n các thông tin vào b&#7843;ng\r\n"
			+ "thêm khách hàng sau &#273;ó ch&#7885;n nút “Thêm”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=366 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/TKH2.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>Khi thêm thành công h&#7879; th&#7889;ng s&#7867;\r\n"
			+ "hi&#7879;n th&#7883; thông báo nh&#432; hình bên d&#432;&#7899;i.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=681 height=364 id=\"Picture 3\"\r\n" + "src='file:/"
			+ Paths.get("Img/TKH3.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	public static final String XEM_CHI_TIET_KHACH_HANG = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>B1: &#7902; giao\r\n"
			+ "di&#7879;n khách hàng ch&#7885;n khách hàng b&#7841;n mu&#7889;n xem chi ti&#7871;t\r\n"
			+ "sau &#273;ó ch&#7885;n vào nút “Xem chi ti&#7871;t”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'><img width=681\r\n"
			+ "height=364 id=\"Picture 3\"\r\n" + "src='file:/" + Paths.get("Img/XCTKH1.png").toAbsolutePath() + "'"
			+ "+\r\n" + "</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>Khi thao tác thành\r\n"
			+ "công h&#7879; th&#7889;ng s&#7867; hi&#7875;n th&#7883; giao di&#7879;n chi ti&#7871;t\r\n"
			+ "kháhc hàng nh&#432; hình bên d&#432;&#7899;i.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'><img width=680\r\n"
			+ "height=363 id=\"Picture 4\"\r\n" + "src='file:/" + Paths.get("Img/XCTKH2.png").toAbsolutePath() + "'"
			+ "+\r\n" + "</span></p>\r\n" + "\r\n" + "<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>\r\n" + "\r\n" + "</div>\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	public static final String TIM_KIEM_HOP_DONG = "<html>\r\n" + "\r\n" + "<head>\r\n" + "\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào tiêu chí mu&#7889;n tìm ki&#7871;m.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2:</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>\r\n"
			+ "Nh&#7853;p thông tin b&#7841;n mu&#7889;n tìm ki&#7871;m vào ô tìm ki&#7871;m.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=555 height=346 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/TKHopDong1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, table&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>Ch&#432;&#417;ng trình s&#7867; hi&#7879;n\r\n"
			+ "th&#7883; danh sách các h&#7907;p &#273;&#7891;ng tìm ki&#7871;m &#273;&#432;&#7907;c\r\n"
			+ "theo tiêu chí &#273;ã &#273;&#432;&#7907;c ch&#7885;n.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=551 height=346 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/TKHopDong2.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, text, application, table&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	// NHÂN VIÊN HÀNH CHÍNH
	public static final String THEM_NHAN_VIEN_HANH_CHINH = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào bi&#7875;u t&#432;&#7907;ng nhân viên &#7903; thanh &#273;i&#7873;u\r\n"
			+ "khi&#7875;n &#7903; phía bên trái màn hình</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span style='position:absolute;z-index:251660288;left:0px;\r\n"
			+ "margin-left:57px;margin-top:246px;width:62px;height:45px'></span><span\r\n"
			+ "style='position:absolute;z-index:251659264;left:0px;margin-left:124px;\r\n"
			+ "margin-top:246px;width:131px;height:45px'></span><span\r\n"
			+ "lang=EN-US style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'><img\r\n"
			+ "width=625 height=389 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/THÊM NHÂN VIÊN_B1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#272;i&#7873;n &#273;&#7847;y &#273;&#7911; thông tin vào các tr&#432;&#7901;ng\r\n"
			+ "và ch&#7885;n nút “Thêm”</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=618 height=390 id=\"Picture 7\"\r\n" + "src='file:/"
			+ Paths.get("Img/THÊM NHÂN VIÊN_B2.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	public static final String XOA_NHAN_VIEN_HANH_CHINH = "<html>\r\n" + "\r\n" + "<head>\r\n" + "\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>B1</span></b><span\r\n"
			+ "lang=EN-US style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#7902; b&#7843;ng danh sách nhân viên hành chính ch&#7885;n vào nhân viên mà b&#7841;n\r\n"
			+ "mu&#7889;n xóa.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>B2</span></b><span\r\n"
			+ "lang=EN-US style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào nút “Xóa”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>B3</span></b><span\r\n"
			+ "lang=EN-US style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Xác nhân thao tác c&#7911;a b&#7841;n, Ch&#7885;n vào “Yes” &#273;&#7875; ti&#7871;n\r\n"
			+ "hành xóa (ch&#7885;n “No” n&#7871;u b&#7841;n không mu&#7889;n xóa).</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'><img width=654\r\n"
			+ "height=410 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/Xóa nhân viên hành chính.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
	public static final String SUA_NHAN_VIEN_HANH_CHINH = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1:</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>\r\n"
			+ "Ch&#7885;n nhân viên hành chính mu&#7889;n s&#7917;a &#7903; b&#7843;ng “Danh\r\n"
			+ "sách nhân viên hành chính”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2: </span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>Ch&#7885;n\r\n"
			+ "vào nút “S&#7917;a”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=618 height=388 id=\"Picture 5\"\r\n" + "src='file:/"
			+ Paths.get("Img/Sửa nhân viên hành chính.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B3: </span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>Ch&#7885;n\r\n"
			+ "và nh&#7853;p thông tin vào các tr&#432;&#7901;ng thông tin c&#7911;a nhân viên\r\n"
			+ "hành chính.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B4: </span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>Ch&#7885;n\r\n"
			+ "nút “C&#7853;p nh&#7853;t”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'><img width=617 height=385\r\n" + "id=\"Picture 6\" "
			+ "src='file:/" + Paths.get("Img/Sửa nhân viên hành chính _1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></b></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>&nbsp;</span></b></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B5: </span></b><span lang=EN\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>Xác\r\n"
			+ "nh&#7853;n yêu c&#7847;u và ch&#7885;n “Yes”</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'><img width=620 height=389\r\n" + "id=\"Picture 7\" "
			+ "src='file:/" + Paths.get("Img/sửa nhân viên hành chính_2.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></b></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
	public static final String TIM_NHAN_VIEN_HANH_CHINH = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n tiêu chí mu&#7889;n tìm ki&#7871;m.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Nh&#7853;p thông tin mu&#7889;n tìm ki&#7871;m vào ô</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=594 height=369 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/Tìm kiếm nhân viên hành chính.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application, table, Excel&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>Sau &#273;ó h&#7879; th&#7889;ng s&#7867;\r\n"
			+ "hi&#7879;n th&#7883; danh sách k&#7871;t qu&#7843; tìm ki&#7871;m &#273;&#432;&#7907;c\r\n"
			+ "&#7903; b&#7843;ng.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=591 height=371 id=\"Picture 3\"\r\n" + "src='file:/"
			+ Paths.get("Img/Tìm kiếm nhân viên hành chính_1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
	public static final String XEMCT_NHAN_VIEN_HANH_CHINH = "<html>\r\n" + "\r\n" + "<head>\r\n" + "\r\n"
			+ "<style>\r\n" + "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n"
			+ "	{font-family:\"Cambria Math\";\r\n" + "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n"
			+ "	{font-family:Calibri;\r\n" + "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#7902; b&#7843;ng danh sách nhân viên hành chính ch&#7885;n vào nhân viên mà b&#7841;n\r\n"
			+ "mu&#7889;n xem chi ti&#7871;t</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào nút “Xem chi ti&#7871;t”</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=606 height=377 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/Xem chi tiết nhân viên hành chính.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>Sau khi thao tác thành công h&#7879; th&#7889;ng\r\n"
			+ "xe hi&#7875;n th&#7883; b&#7843;ng chi ti&#7871;t nhân viên nh&#432; sau: </span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=598 height=373 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/Xem chi tiết nhân viên hành chính_1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	public static final String THEM_NV_KI_THUAT = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n" + "<!--\r\n"
			+ " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#7902; b&#7843;ng nhân viên k&#297; thu&#7853;t, ch&#7885;n vào nút “Thêm”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=610 height=382 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/Thêm nhân viên kĩ thuật.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n lo&#7841;i nhân viên là “nhân viên k&#7929; thu&#7853;t”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B3</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n và nh&#7853;p thông tin c&#7911;a nhân viên k&#7929; thu&#7853;t vào\r\n"
			+ "các tr&#432;&#7901;ng.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B4</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào nút “Thêm”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=622 height=388 id=\"Picture 3\"\r\n" + "src='file:/"
			+ Paths.get("Img/Thêm nhân viên kĩ thuật_2.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
	public static final String XOA_NV_KI_THUAT = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n" + "<!--\r\n"
			+ " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#7902; b&#7843;ng nhân viên k&#7929; thu&#7853;t ch&#7885;n nhân viên mu&#7889;n\r\n"
			+ "xóa</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào nút “Xóa”</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B3</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Xác nh&#7853;n yêu c&#7847;u và ch&#7885;n “Yes”</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=626 height=391 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/Xóa nhân viên kĩ thuật.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n" + "</div>\r\n"
			+ "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
	public static final String SUA_NV_KI_THUAT = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n" + "<!--\r\n"
			+ " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#7902; b&#7843;ng nhân viên k&#7929; thu&#7853;t ch&#7885;n nhân viên k&#297;\r\n"
			+ "thu&#7853;t mu&#7889;n c&#7853;p nh&#7853;t.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào nút “S&#7917;a”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US><img width=602 height=377 id=\"Picture 2\"\r\n"
			+ "src='file:/"+Paths.get("Img/Sửa nhân viên Ki Thuat.png").toAbsolutePath()+"'"+"+\r\n"
			+ "alt=\"A picture containing table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B3</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n và &#273;i&#7873;n các thông tin mu&#7889;n c&#7853;p nh&#7853;t.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B4</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Ch&#7885;n vào nút s&#7917;a.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B5</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Xác nh&#7853;n yêu c&#7847;u và ch&#7885;n “yes”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=602 height=374 id=\"Picture 3\"\r\n"
			+ "src='file:/"+Paths.get("Img/Sửa nhân viên Ki Thuat_1.png").toAbsolutePath()+"'"+"+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n" + "</div>\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
	public static final String TIM_KIEM_NV_KI_THUAT = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n" + "<!--\r\n"
			+ " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B1</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "&#7902; b&#7843;ng nhân viên k&#7929; thu&#7853;t ch&#7885;n vào tiêu chí mu&#7889;n\r\n"
			+ "tìm ki&#7871;m.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=618 height=385 id=\"Picture 1\"\r\n" + "src='file:/"
			+ Paths.get("Img/Tìm kiếm nhân viên ki thuậtpng.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Table&#10;&#10;Description automatically generated\"></span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><b><span lang=EN-US style='font-size:20.0pt;line-height:\r\n"
			+ "107%;font-family:\"Times New Roman\",serif'>B2</span></b><span lang=EN-US\r\n"
			+ "style='font-size:20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>:\r\n"
			+ "Nh&#7853;p thông tin mu&#7889;n tìm ki&#7871;m vào ô.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>Sau &#273;ó ch&#432;&#417;ng trình s&#7867;\r\n"
			+ "hi&#7875;n th&#7883; danh sách k&#7871;t qu&#7843; tìm ki&#7871;m &#273;&#432;&#7907;c</span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'><img width=610 height=378 id=\"Picture 2\"\r\n" + "src='file:/"
			+ Paths.get("Img/Tìm kiếm nhân viên ki thuật_1png.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "</div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
}
