package constant;

import java.nio.file.Paths;

public class HuongDanSuDungConstant {
	public static final String TEST = "<!DOCTYPE html>\r\n" + "<html>\r\n" + "<head>\r\n"
			+ "	<title>Bài 7</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "	<p><img src='file:/"
			+ Paths.get("Img/img7.png").toAbsolutePath()
			+ "' width=\"70\" height=\"70\" alt=\"img\">A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<p><img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"middle\" width=\"70\" height=\"70\" alt=\"img\">A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<p><img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"top\" width=\"70\" height=\"70\" alt=\"img\">A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"right\" width=\"70\" height=\"70\" alt=\"img\">\r\n"
			+ "	<p>A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	<img src='file:/" + Paths.get("Img/img7.png").toAbsolutePath()
			+ "' align=\"left\" width=\"70\" height=\"70\" alt=\"img\">\r\n"
			+ "	<p>A smile is a facial expression formed primarily by flexing the muscles at the sides of the mouth. It is  believed it takes about 80 muscles to smile. Some smiles include a contraction of the muscles at the corner of the eyes, an action known as a \"Duchenne smile\". Smiles performed without the eye contraction may be perceived as insincere.</p>\r\n"
			+ "	<hr>\r\n" + "	\r\n" + "</body>\r\n" + "</html>";

	public static final String LAP_HOA_DON = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Thêm khách hàng</h1>\r\n"
			+ "    <hr>\r\n" + "    <p>B1: Chọn vào nút “Lập hóa đơn” ở giao diện trang chủ</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/LapHoaDon1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B2: Điền thông tin số CMT hoặc SĐT để lấy thông tin của khách hàng đã có sẵn trong hệ thống.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/LapHoaDon2.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Khi thông tin của khách hàng dược lấy lên nó sẻ có dạng như hình sau: </p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/LapHoaDon3.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B3: Chọn xe mà khách hàng muốn đặt sau đó chọn vào nút “Thêm”, xe vừa thao tác sẻ được thêm vào bảng hóa đơn.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/LapHoaDon4.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B4: Nhập tiền khách trả vào ô “Tiền khách trả, hệ thống sẻ hiện thị tiền thừa ở ô “Tiền trả lại”.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/LapHoaDon5.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B5: Chọn nút “Lập hóa đơn”. Sau khi lập hóa đơn thành công hệ thống sẻ hiển thị bảng chi tiết hóa đơn như hình bên dưới.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/LapHoaDon6.png").toAbsolutePath() + "' alt=\"\">\r\n" + "    \r\n"
			+ "</body>\r\n" + "</html>";
	public static final String TIM_KIEM_HOA_DON = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Tìm kiếm hóa đơn</h1>\r\n"
			+ "    <hr>\r\n" + "    <p>B1: Ở trang quản lý hóa đơn chọn và tiêu chí muốn tìm kiếm hóa đơn.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/TimHoaDon1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B2: Nhập từ khóa muốn tìm kiếm vào ô tìm kiếm. Hệ thống sẻ hiển thị bảng danh sách hóa đơn theo từ khóa đã nhập</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/TimHoaDon2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "    \r\n"
			+ "    \r\n" + "</body>\r\n" + "</html>";

	public static final String GIOI_THIEU = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    h2 {\r\n" + "        text-align: center;\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n"
			+ "    h3 {\r\n" + "        font-size: 20px;\r\n" + "    }\r\n" + "\r\n" + "    p {\r\n" + "\r\n"
			+ "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n" + "        font-size: 40px;\r\n"
			+ "    }\r\n" + "\r\n" + "    b {\r\n" + "        font-size: 18px;\r\n" + "    }\r\n" + "\r\n"
			+ "    li {\r\n" + "        font-size: 15px;\r\n" + "    }\r\n" + "\r\n" + "    /* ul{\r\n"
			+ "        text-align: center;\r\n" + "    }\r\n" + "\r\n" + "    li{\r\n"
			+ "        text-align: center;\r\n" + "    } */\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n"
			+ "<h1 style=\"text-align: center;\">Giới Thiệu</h1>\r\n" + "<hr>\r\n"
			+ "<h2>Quản lý mua bán xe máy tại cửa hàng Motor Cycle Việt Nam. </h2>\r\n"
			+ "<h2>Version: 2020-11 (1.0.0.0)</h2>\r\n" + "<div style=\"margin-left: 400px;\">\r\n" + "<img src='file:/"
			+ Paths.get("Img/layer 1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "</div>\r\n"
			+ "<h3 style=\"text-align: center;\">Giảng viên hướng dẫn: ThS.Trần Thị Anh Thi</h3>\r\n" + "<hr>\r\n"
			+ "<div>\r\n" + "    <ul><b>Thành viên nhóm 7</b>\r\n"
			+ "        <li>Huỳnh Anh Tiên - 18065341 (Nhóm trưởng)</li>\r\n"
			+ "        <li>Nguyễn Trần Nhật Hào - 18055671</li>\r\n" + "        <li>Trần Hoàng Phúc - 18072731</li>\r\n"
			+ "        <li>Mai Thanh Trọng - 18064861</li>\r\n" + "    </ul>\r\n" + "</div>\r\n" + "\r\n" + "<body>\r\n"
			+ "\r\n" + "</body>\r\n" + "\r\n" + "</html>";

	public static final String TIM_KIEM_HOP_DONG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n"
			+ "        img{\r\n" + "            width: 60%;\r\n" + "        }\r\n" + "    </style>\r\n" + "\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Tìm kiếm hợp đồng</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Tìm kiếm hợp đồng</h1>\r\n" + "        <hr>\r\n"
			+ "        <p>B1: Chọn vào tiêu chí muốn tìm kiếm.</p>\r\n"
			+ "        <p>B2: Nhập thông tin bạn muốn tìm kiếm vào ô tìm kiếm.</p>\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n" + "        <img src=\"file:\\"
			+ Paths.get("Img/TimHopDong1.png").toAbsolutePath() + "\" alt=\"\">\r\n" + "\r\n" + "        <br>\r\n"
			+ "        <p>Chương trình sẻ hiện thị danh sách các hợp đồng tìm kiếm được theo tiêu chí đã được chọn.</p>\r\n"
			+ "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n" + "        <img src='file:\\"
			+ Paths.get("Img/TimHopDong2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "    </div>\r\n"
			+ "\r\n" + "</body>\r\n" + "\r\n" + "</html>";

	public static final String TIM_KIEM_HOP_DONG_THEO_NGAY = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Tìm kiếm hợp đồng theo ngày</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Tìm kiếm hợp đồng</h1>\r\n" + "        <hr>\r\n"
			+ "        <p> Chọn vào ngày, tháng, năm muốn tìm kiếm hợp đồng</p>\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "        <br>\r\n" + "\r\n" + "        <img  src='file:\\"
			+ Paths.get("Img/TKHopDongTheoNgay1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "        <br>\r\n"
			+ "        <p>Chương trình sẻ hiển thị danh sách hợp đồng tương ứng với ngày tìm kiếm</p>\r\n" + "\r\n"
			+ "\r\n" + "        <br>\r\n" + "\r\n" + "        <img  src='file:\\"
			+ Paths.get("Img/TKHopDongTheoNgay2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n"
			+ "    </div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>";

	public static final String XEM_CHI_TIET_HOP_DONG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Xem chi tiết hợp đồng</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Xem chi tiết hợp đồng</h1>\r\n"
			+ "        <hr>\r\n" + "        <p>B1: Chọn vào hợp đồng mà bạn muốn xem chi tiết.</p>\r\n"
			+ "        <p>B2: Chọn vào nút “Xem chi tiết”</p>\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "        <br>\r\n" + "\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/ChiTietHopDong1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "        <br>\r\n"
			+ "        <p>Chương trình hiển thị bảng “Chi tiết hợp đồng xe máy”</p>\r\n" + "\r\n" + "\r\n"
			+ "        <img  src='file:/" + Paths.get("Img/ChiTietHopDong2.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    </div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>";

	public static final String SUA_NHAN_VIEN_KY_THUAT = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Sửa nhân viên kĩ thuật</title>\r\n" + "</head>\r\n" + "<body>\r\n"
			+ "    <div style=\"margin: 50px; font-size: 20px;\">\r\n" + "        <h1>Sửa nhân viên kĩ thuật</h1>\r\n"
			+ "        <hr>\r\n"
			+ "        <p>B1: Ở bảng nhân viên kỹ thuật chọn nhân viên kĩ thuật muốn cập nhật.</p>\r\n"
			+ "        <p>B2: Chọn vào nút “Sửa”.</p>\r\n" + "        <br>\r\n"
			+ "        <img  src=\"../IMG/nhân viên kĩ thuật/SuaNVKT1.png\" alt=\"\">\r\n" + "        <br>\r\n"
			+ "        <p>B3: Chọn và điền các thông tin muốn cập nhật.</p>\r\n"
			+ "        <p>B4: Chọn vào nút sửa.</p>\r\n" + "        <p>B5: Xác nhận yêu cầu và chọn “yes”.</p>\r\n"
			+ "        <br>\r\n" + "        <img  src=\"../IMG/nhân viên kĩ thuật/SuaNVKT2.png\" alt=\"\">\r\n"
			+ "    </div>\r\n" + "</body>\r\n" + "</html>";

	// KHÁCH HÀNG
	public static final String XOA_KHACH_HANG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Xóa khách hàng</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Ở giao diện quản lý khách hàng chọn vào khách hàng muốn xóa </p>\r\n"
			+ "    <p>- Chọn xóa và bấm vào nút Yes</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/XoaKhachHang.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String SUA_KHACH_HANG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Cập nhật khách hàng</h1>\r\n"
			+ "    <hr>\r\n"
			+ "    <p>B1: Ở giao diện Quản lý khách hàng chọn vào khách hàng bạn muốn sửa và chọn vào nút sửa.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/CapNhatKH0.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B2: Sửa lại các thông tin mà bạn muốn thay đổi trên giao diện “Cập nhật thông tin khách hàng” và chọn nút “Lưu”.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/CapNhatKH1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Hệ thống sẻ xuất hiện 1 yêu cầu để xác nhận và khi chọn “yes” thì sửa khách hàng đã thành công và sẻ hiển thị thông báo như hình bên.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/CapNhatKH2.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "</body>\r\n" + "</html>";
	public static final String TIM_KIEM_KHACH_HANG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Tìm kiếm khách hàng</h1>\r\n"
			+ "    <p>B1: Ở trang quản lý khách hàng chọn tiêu chí mà bạn muốn tìm kiếm.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/TimKH1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B2: Nhập từ khóa bạn muốn tìm kiếm và ô tìm kiếm</p>\r\n"
			+ "    <p>Hệ thống sẻ hiển thị bảng danh sách các kết quả tìm được</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/TimKH2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "</body>\r\n"
			+ "</html>";

	public static final String THEM_KHACH_HANG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Thêm khách hàng</h1>\r\n"
			+ "    <hr>\r\n" + "    <p>B1: Ở trang quản lý hóa đơn chọn và tiêu chí muốn tìm kiếm hóa đơn.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemKhachHang1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>B2: Nhập từ khóa muốn tìm kiếm vào ô tìm kiếm. Hệ thống sẻ hiển thị bảng danh sách hóa đơn theo từ khóa đã nhập</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemKhachHang2.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Khi thêm thành công hệ thống sẻ hiện thị thông báo như hình bên dưới.</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemKhachHang3.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    \r\n" + "    \r\n" + "</body>\r\n" + "</html>";

	public static final String XEM_CHI_TIET_KHACH_HANG = "<html>\r\n" + "\r\n" + "<head>\r\n" + "<style>\r\n"
			+ "<!--\r\n" + " /* Font Definitions */\r\n" + " @font-face\r\n" + "	{font-family:\"Cambria Math\";\r\n"
			+ "	panose-1:2 4 5 3 5 4 6 3 2 4;}\r\n" + "@font-face\r\n" + "	{font-family:Calibri;\r\n"
			+ "	panose-1:2 15 5 2 2 2 4 3 2 4;}\r\n" + " /* Style Definitions */\r\n"
			+ " p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n" + "	{margin-top:6.0pt;\r\n" + "	margin-right:0in;\r\n"
			+ "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n" + "	text-indent:28.35pt;\r\n"
			+ "	line-height:107%;\r\n" + "	font-size:11.0pt;\r\n" + "	font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoChpDefault\r\n" + "	{font-family:\"Calibri\",sans-serif;\r\n"
			+ "	letter-spacing:-.5pt;}\r\n" + ".MsoPapDefault\r\n" + "	{margin-top:6.0pt;\r\n"
			+ "	margin-right:0in;\r\n" + "	margin-bottom:8.0pt;\r\n" + "	margin-left:0in;\r\n"
			+ "	text-indent:28.35pt;\r\n" + "	line-height:107%;}\r\n" + "@page WordSection1\r\n"
			+ "	{size:595.3pt 841.9pt;\r\n" + "	margin:56.7pt 42.55pt 56.7pt 42.55pt;}\r\n" + "div.WordSection1\r\n"
			+ "	{page:WordSection1;}\r\n" + "-->\r\n" + "</style>\r\n" + "\r\n" + "</head>\r\n" + "\r\n"
			+ "<body lang=VI>\r\n" + "\r\n" + "<div class=WordSection1>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>B1: &#7902; giao\r\n"
			+ "di&#7879;n khách hàng ch&#7885;n khách hàng b&#7841;n mu&#7889;n xem chi ti&#7871;t\r\n"
			+ "sau &#273;ó ch&#7885;n vào nút “Xem chi ti&#7871;t”.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'><img width=681\r\n"
			+ "height=364 id=\"Picture 3\"\r\n" + "src='file:/" + Paths.get("Img/XCTKH1.png").toAbsolutePath() + "'"
			+ "+\r\n" + "</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>Khi thao tác thành\r\n"
			+ "công h&#7879; th&#7889;ng s&#7867; hi&#7875;n th&#7883; giao di&#7879;n chi ti&#7871;t\r\n"
			+ "kháhc hàng nh&#432; hình bên d&#432;&#7899;i.</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n"
			+ "<p class=MsoNormal style='text-indent:0in'><span lang=EN-US style='font-size:\r\n"
			+ "20.0pt;line-height:107%;font-family:\"Times New Roman\",serif'><img width=680\r\n"
			+ "height=363 id=\"Picture 4\"\r\n" + "src='file:/" + Paths.get("Img/XCTKH2.png").toAbsolutePath() + "'"
			+ "+\r\n" + "</span></p>\r\n" + "\r\n" + "<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>\r\n" + "\r\n" + "</div>\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>\r\n" + "";

	// NHÂN VIÊN HÀNH CHÍNH
	public static final String THEM_NHAN_VIEN_HANH_CHINH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Thêm nhân viên hành chính</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    \r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Thêm nhân viên hành chính</h1>\r\n"
			+ "        <hr>\r\n"
			+ "        <p><b>B1</b>: Chọn vào biểu tượng nhân viên ở thanh điều khiển ở phía bên trái màn hình</p>\r\n"
			+ "        <br>\r\n" + "    \r\n" + "        <img src='file:/"
			+ Paths.get("Img/ThemNVHC2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "        <br>\r\n"
			+ "        <p><b>B2</b>: Điền đầy đủ thông tin vào các trường và chọn nút “Thêm”</p>\r\n"
			+ "        <br>\r\n" + "\r\n" + "        <img src='file:/" + Paths.get("Img/ThemNVHC3.png").toAbsolutePath()
			+ "' alt=\"\">\r\n" + "\r\n" + "    </div>\r\n" + "\r\n" + "</body>\r\n" + "</html>";

	public static final String XOA_NHAN_VIEN_HANH_CHINH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Xóa nhân viên hành chính</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Xóa nhân viên hành chính</h1>\r\n"
			+ "        <hr>\r\n"
			+ "        <p><b>B1</b>: Ở bảng danh sách nhân viên hành chính chọn vào nhân viên mà bạn muốn xóa.</p>\r\n"
			+ "        <p><b>B2</b>: Chọn vào nút “Xóa”.</p>\r\n"
			+ "        <p><b>B3</b>: Xác nhân thao tác của bạn, Chọn vào “Yes” để tiến hành xóa (chọn “No” nếu bạn không muốn xóa).</p>\r\n"
			+ "\r\n" + "        <br>\r\n" + "\r\n" + "        <img src='file:/"
			+ Paths.get("Img/XoaNVHC.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "    </div>\r\n"
			+ "\r\n" + "</body>\r\n" + "\r\n" + "</html>";
	public static final String SUA_NHAN_VIEN_HANH_CHINH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Sửa nhân viên hành chính</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1 >Sửa nhân viên hành chính</h1>\r\n"
			+ "        <hr>\r\n"
			+ "        <p><b>B1</b>: Chọn nhân viên hành chính muốn sửa ở bảng “Danh sách nhân viên hành chính”.</p>\r\n"
			+ "        <p><b>B2</b>: Chọn vào nút “Sửa”.</p>\r\n" + "        <br>\r\n" + "\r\n"
			+ "        <img  src='file:/" + Paths.get("Img/SuaNVHC1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "        <br>\r\n"
			+ "        <p><b>B3</b>: Chọn và nhập thông tin vào các trường thông tin của nhân viên hành chính.</p>\r\n"
			+ "        <p><b>B4</b>: Chọn nút “Cập nhật”.</p>\r\n" + "\r\n" + "        <br>\r\n" + "\r\n"
			+ "        <img  src='file:/" + Paths.get("Img/SuaNVHC2.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "        <br>\r\n" + "        <p><b>B5</b>: Xác nhận yêu cầu và chọn “Yes”</p>\r\n"
			+ "        <img  src='file:/" + Paths.get("Img/SuaNVHC3.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "    </div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>";
	public static final String TIM_NHAN_VIEN_HANH_CHINH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Tìm kiếm nhân viên hành chính</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Tìm kiếm nhân viên hành chính</h1>\r\n"
			+ "        <hr>\r\n" + "        <p><b>B1</b>: Chọn tiêu chí muốn tìm kiếm.</p>\r\n"
			+ "        <p><b>B2</b>: Nhập thông tin muốn tìm kiếm vào ô</p>\r\n" + "        \r\n" + "\r\n"
			+ "        <br>\r\n" + "\r\n" + "        <img  src='file:/" + Paths.get("Img/TimNVHC1.png").toAbsolutePath()
			+ "' alt=\"\">\r\n" + "\r\n" + "        <br>\r\n"
			+ "        <p>Sau đó hệ thống sẻ hiện thị danh sách kết quả tìm kiếm được ở bảng.</p>\r\n" + "\r\n"
			+ "        <br>\r\n" + "\r\n" + "        <img  src='file:/" + Paths.get("Img/TimNVHC1.png").toAbsolutePath()
			+ "' alt=\"\">\r\n" + "        \r\n" + "\r\n" + "    </div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";

	// nhan vien ki thuat
	public static final String THEM_NV_KI_THUAT = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Thêm nhân viên kĩ thuật</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Thêm nhân viên kĩ thuật</h1>\r\n"
			+ "        <hr>\r\n" + "        <p><b>B1</b>: Ở bảng nhân viên kĩ thuật, chọn vào nút “Thêm”.</p>\r\n"
			+ "\r\n" + "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/ThemNVKT1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "        <br>\r\n"
			+ "        <p><b>B2</b>: Chọn loại nhân viên là “nhân viên kỹ thuật”.</p>\r\n"
			+ "        <p><b>B3</b>: Chọn và nhập thông tin của nhân viên kỹ thuật vào các trường.</p>\r\n"
			+ "        <p><b>B4</b>: Chọn vào nút “Thêm”.</p>\r\n" + "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n"
			+ "        <img  src='file:/" + Paths.get("Img/ThemNVKT2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "\r\n" + "    </div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>";
	public static final String XOA_NV_KI_THUAT = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Xóa nhân viên kĩ thuật</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Xóa nhân viên kĩ thuật</h1>\r\n"
			+ "        <hr>\r\n" + "        <p>B1: Ở bảng nhân viên kỹ thuật chọn nhân viên muốn xóa</p>\r\n"
			+ "        <p>B2: Chọn vào nút “Xóa”</p>\r\n" + "        <p>B3: Xác nhận yêu cầu và chọn “Yes”</p>\r\n"
			+ "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/XoaNVKT1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "    \r\n" + "\r\n"
			+ "    </div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>";
	public static final String SUA_NV_KI_THUAT = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Sửa nhân viên kĩ thuật</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Sửa nhân viên kĩ thuật</h1>\r\n"
			+ "        <hr>\r\n"
			+ "        <p>B1: Ở bảng nhân viên kỹ thuật chọn nhân viên kĩ thuật muốn cập nhật.</p>\r\n"
			+ "        <p>B2: Chọn vào nút “Sửa”.</p>\r\n" + "\r\n" + "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n"
			+ "        <img  src='file:/" + Paths.get("Img/SuaNVKT1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "        <br>\r\n" + "        <p>B3: Chọn và điền các thông tin muốn cập nhật.</p>\r\n"
			+ "        <p>B4: Chọn vào nút sửa.</p>\r\n" + "        <p>B5: Xác nhận yêu cầu và chọn “yes”.</p>\r\n"
			+ "\r\n" + "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/SuaNVKT2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "    </div>\r\n"
			+ "\r\n" + "</body>\r\n" + "\r\n" + "</html>"
			+ "font-family:\"Times New Roman\",serif'><img width=602 height=374 id=\"Picture 3\"\r\n" + "src='file:/"
			+ Paths.get("Img/Sửa nhân viên Ki Thuat_1.png").toAbsolutePath() + "'" + "+\r\n"
			+ "alt=\"Graphical user interface, application&#10;&#10;Description automatically generated\"></span></p>\r\n"
			+ "\r\n" + "<p class=MsoNormal><span lang=EN-US style='font-size:20.0pt;line-height:107%;\r\n"
			+ "font-family:\"Times New Roman\",serif'>&nbsp;</span></p>\r\n" + "\r\n" + "</div>\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
	public static final String TIM_KIEM_NV_KI_THUAT = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Tìm kiếm nhân viên kĩ thuật</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "\r\n"
			+ "    <div style=\"margin: 50px;\">\r\n" + "        <h1>Tìm kiếm nhân viên kĩ thuật</h1>\r\n"
			+ "        <hr>\r\n"
			+ "        <p><b>B1</b>: Ở bảng nhân viên kỹ thuật chọn vào tiêu chí muốn tìm kiếm.</p>\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "        <br>\r\n" + "\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/TimKiemNVKT1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "        <br>\r\n"
			+ "        <p>B2: Nhập thông tin muốn tìm kiếm vào ô.</p>\r\n"
			+ "        <p>Sau đó chương trình sẻ hiển thị danh sách kết quả tìm kiếm được</p>\r\n" + "\r\n" + "\r\n"
			+ "\r\n" + "        <br>\r\n" + "\r\n" + "        <img  src='file:/"
			+ Paths.get("Img/TimKiemNVKT1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n"
			+ "    </div>\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>";

	// thống kê
	public static final String THONG_KE_THEO_NGAY = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Thống kê theo ngày</h1>\r\n"
			+ "    <p>- Ở giao diện Thống kê chọn vào “Tổng doanh thu trong ngày”</p>\r\n"
			+ "    <p>- Hệ thống sẻ hiện thị bảng daonh thu trong ngày đó</p>\r\n"
			+ "    <p>- Ngoài ra bạn có thể lựa chọn “ngày” và dạng thống kê( biểu đồ, số liệu).</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThongKeNgay.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "</body>\r\n" + "</html>";
	public static final String THONG_KE_THEO_THANG = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Thống kê theo tháng</h1>\r\n"
			+ "    <p>- Ở giao diện thống kê chọn vào “Tổng thu trong tháng”.</p>\r\n"
			+ "    <p>- Hệ thống sẻ hiển thị các biểu đồ dưới dạng bảng thống kê về doanh thi trong tháng hiện tại.</p>\r\n"
			+ "    <p>- Ngoài ra bạn có thể chọn tháng theo năm và dạng thống kê (biểu đồ, text)..</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThongKeThang.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "</body>\r\n" + "</html>";
	public static final String THONG_KE_THEO_NAM = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Thống kê theo năm</h1>\r\n"
			+ "    <p>- Ở giao diện thống kê chọn vào “Tổng thu trong năm”.</p>\r\n"
			+ "    <p>- Hệ thống sẻ hiện thị các biểu đồ dưới dạng bảng về tổng thu trong năm hiện tại</p>\r\n"
			+ "    <p>- Ngoài ra bạn còn có thể chọn năm muốn thống kê hoặc dạng thống kê (biểu đồ, số liệu</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThongKeNam1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Khi chọn dạng thống kê “số liệu” hệ thống sẻ hiện thị như hình bên dưới:</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThongKeNam2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "</body>\r\n" + "</html>";
	// Xe May

	public static final String XOA_XE_MAY = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Xóa xe máy</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý xe máy chọn vào chế độ xem từng xe </p>\r\n"
			+ "    <p>- Chọn vào xe muốn xóa</p>\r\n" + "    <p>- Chọn xóa và bấm vào nút Yes</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/XoaXeMay.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>";

	public static final String THEM_XE_MAY = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Thêm xe máy</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện trang chủ chọn \"Thêm xe máy\".</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemXeMay1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>- Điền đầy đủ các thông tin của xe máy sau đó chọn nút thêm</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemXeMay2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "</body>\r\n" + "</html>";
	public static final String SUA_XE_MAY = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Cập nhật xe máy</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý xe máy chọn xe máy muốn cập nhật.</p>\r\n"
			+ "    <p>- Chọn nút sửa</p>\r\n" + "    <img src='file:/" + Paths.get("Img/SuaXeMay1.png").toAbsolutePath()
			+ "' alt=\"\">\r\n" + "    <p>- Chọn và sửa các trường muộn cập nhật</p>\r\n"
			+ "    <p>- Bấm nút lưu</p>\r\n" + "    <img src='file:/" + Paths.get("Img/SuaXeMay2.png").toAbsolutePath()
			+ "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n" + "</body>\r\n" + "</html>";
	public static final String TIM_XE_MAY = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Tìm xe máy</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý xe máy chọn tiêu chí tìm kiếm.</p>\r\n"
			+ "    <p>- Nhập thông tin muốn tìm kiếm</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/TimXe1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>- Ngoài ra có thể kết hợp tìm kiếm theo nhiều tiêu chí khác nhau</p>\r\n"
			+ "    <p>- Có thể gộp nhóm xe hoặc xem từng xe</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/TimXe1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "</body>\r\n" + "</html>";

	// Bảo hành

	public static final String THEM_BAO_HANH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "    <style>\r\n"
			+ "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n" + "        }\r\n"
			+ "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n" + "    </style>\r\n"
			+ "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n" + "    <h1>Thêm phiếu bảo hành</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện trang chủ chọn vào nút \"Bảo hành\"</p>\r\n"
			+ "    <p>- Nhập thông tin muốn tìm kiếm</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemBaoHanh1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>- Chọn đối tượng muốn thêm phiếu bảo hành và chọn xem chi tiết</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemBaoHanh2.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>- Chọn đợt bảo hành và bấm vào nút thêm</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemBaoHanh3.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>- Thêm vào các danh mục bảo hành và chọn \"Lưu\"</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemBaoHanh4.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "</body>\r\n" + "</html>";
	public static final String THEM_DANH_MUC_BAO_HANH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n"
			+ "    <style>\r\n" + "        p{\r\n" + "            \r\n" + "            font-size: 30px;\r\n"
			+ "        }\r\n" + "        h1{\r\n" + "            font-size: 40px;\r\n" + "        }\r\n" + "\r\n"
			+ "    </style>\r\n" + "<head>\r\n" + "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "<body>\r\n"
			+ "    <h1>Thêm danh mục bảo hành</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Ở giao diện quản lý bảo hành chọn Danh mục bảo hành</p>\r\n"
			+ "    <p>- Điền tên danh mục bảo hành và chọn vào nút thêm</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemDMBH.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "</html>";
	public static final String XOA_DANH_MUC_BAO_HANH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Xóa danh mục bảo hành</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Ở giao diện quản lý bảo hành chọn Danh mục bảo hành</p>\r\n"
			+ "    <p>- Chọn danh mục bảo hành muốn xóa</p>\r\n" + "    <p>- Chọn nút xóa</p>\r\n"
			+ "    <p>- Chọn yes để xác nhận</p>\r\n" + "    <p>-Chọn sửa</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/XoaDMBH.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String SUA_DANH_MUC_BAO_HANH = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Sửa danh mục bảo hành</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Ở giao diện quản lý bảo hành chọn Danh mục bảo hành</p>\r\n"
			+ "    <p>-Chọn danh mục bảo hành muốn sửa</p>\r\n" + "    <p->Sửa tên danh mục bảo hành</p>\r\n"
			+ "    <p>-Chọn sửa</p>\r\n" + "    <img src='file:/" + Paths.get("Img/ThemDMBH.png").toAbsolutePath()
			+ "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n" + "</html>";

	// đổi mật khẩu
	public static final String DOI_MAT_KHAU = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Đổi mật khẩu</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Ở giao diện trang chủ chọn dổi mật khẩu</p>\r\n" + "    <p>- Nhập mật khẩu hiện tại</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/DoiMatKhau1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>- Nhập mật khẩu mới và xác nhận</p>\r\n" + "    <p>- Chọn OK</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/DoiMatKhau2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";

	// Dòng xe
	public static final String THEM_DONG_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Thêm dòng xe</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Trong giao diện quản lý xe máy, click chuột phải vào trường dòng xe </p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemDongXe1.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Hệ thống hiển thị giao diện Quản lý dòng xe</p>\r\n"
			+ "    <p>- Điền tên dòng xe, thuế muốn thêm và chọn \"Thêm\"</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemDongXe2.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String SUA_DONG_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Sửa dòng xe</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý dòng xe chọn vào dòng xe muốn sửa </p>\r\n"
			+ "    <p>- Thay đổi các trường thông tin và bấm nút Sửa </p>\r\n" + "    <p>- Bấm vào nút Yes</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/SuaDongXe.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>";
	public static final String XOA_DONG_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Xóa dòng xe</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý dòng xe chọn vào dòng xe muốn xóa </p>\r\n"
			+ "    <p>- Chọn xóa và bấm vào nút Yes</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/XoaDongXe.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";

	// Hãng xe
	public static final String THEM_HANG_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Thêm hãng xe</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Trong giao diện quản lý xe máy, click chuột phải vào trường hãng xe </p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemHangXe0.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Hệ thống hiển thị giao diện Quản lý hãng xe</p>\r\n"
			+ "    <p>- Điền tên hãng xe muốn thêm và chọn \"Thêm\"</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemHangXe1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String XOA_HANG_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Xóa hãng xe</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý hãng xe chọn vào hãng xe muốn xóa </p>\r\n"
			+ "    <p>- Chọn xóa và bấm vào nút Yes</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/XoaHangXe.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String SUA_HANG_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Sửa hãng xe</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý hãng xe chọn vào hãng xe muốn sửa </p>\r\n"
			+ "    <p>- Thay đổi các trường thông tin và bấm nút Sửa </p>\r\n" + "    <p>- Bấm vào nút Yes</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/SuaHangXe.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>";

	// Loại xe
	public static final String THEM_LOAI_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Thêm loại xe</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Trong giao diện quản lý xe máy, click chuột phải vào trường loại xe </p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemLoaiXe0.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Hệ thống hiển thị giao diện Quản lý loại xe</p>\r\n"
			+ "    <p>- Điền tên loại xe muốn thêm và chọn \"Thêm\"</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemLoaiXe1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String XOA_LOAI_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Xóa loại xe</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý loại xe chọn vào loại xe muốn xóa </p>\r\n"
			+ "    <p>- Chọn xóa và bấm vào nút Yes</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/XoaLoaiXe.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String SUA_LOAI_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Sửa loại xe</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý loại xe chọn vào loại xe muốn sửa </p>\r\n"
			+ "    <p>- Thay đổi các trường thông tin và bấm nút Sửa </p>\r\n" + "    <p>- Bấm vào nút Yes</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/SuaLoaiXe.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>";

	// Xuất xứ
	public static final String THEM_XUAT_XU_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n"
			+ "    <h1>Thêm xuất xứ</h1>\r\n" + "    <hr>\r\n" + "\r\n"
			+ "    <p>- Trong giao diện quản lý xe máy, click chuột phải vào trường xuất xứ </p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/ThemXuatXu0.png").toAbsolutePath() + "' alt=\"\">\r\n"
			+ "    <p>Hệ thống hiển thị giao diện Quản lý xuất xứ</p>\r\n"
			+ "    <p>- Điền tên xuất xứ muốn thêm và chọn \"Thêm\"</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/ThemXuatXu1.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String XOA_XUAT_XU_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Xóa xuất xứ</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý xuất xứ chọn vào xuất xứ muốn xóa </p>\r\n"
			+ "    <p>- Chọn xóa và bấm vào nút Yes</p>\r\n" + "    <img src='file:/"
			+ Paths.get("Img/XoaXuatXu.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n" + "</body>\r\n" + "\r\n"
			+ "</html>";
	public static final String SUA_XUAT_XU_XE = "<!DOCTYPE html>\r\n" + "<html lang=\"en\">\r\n" + "<style>\r\n"
			+ "    p {\r\n" + "\r\n" + "        font-size: 30px;\r\n" + "    }\r\n" + "\r\n" + "    h1 {\r\n"
			+ "        font-size: 40px;\r\n" + "    }\r\n" + "</style>\r\n" + "\r\n" + "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Document</title>\r\n" + "</head>\r\n" + "\r\n" + "<body>\r\n" + "    <h1>Sửa xuất xứ</h1>\r\n"
			+ "    <hr>\r\n" + "\r\n" + "    <p>- Ở giao diện quản lý xuất xứ chọn vào xuất xứ muốn sửa </p>\r\n"
			+ "    <p>- Thay đổi các trường thông tin và bấm nút Sửa </p>\r\n" + "    <p>- Bấm vào nút Yes</p>\r\n"
			+ "    <img src='file:/" + Paths.get("Img/SuaXuatXu.png").toAbsolutePath() + "' alt=\"\">\r\n" + "\r\n"
			+ "</body>\r\n" + "\r\n" + "</html>";
//XÓA XE MÁY, XÓA KHÁCH HÀNG

}
